name: offchain-modules-ci

on:
  push:
    paths:
      - .github/workflows/offchain-modules.yml
      - 'offchain-modules/**'
  pull_request:
    paths:
      - .github/workflows/offchain-modules.yml
      - 'offchain-modules/**'

defaults:
  run:
    working-directory: offchain-modules

jobs:
  eth-contracts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Cache node_modules
#        uses: actions/cache@v2
#        id: yarn-cache
#        with:
#          path: |
#            */node_modules
#          key: node-modules-${{ hashFiles('*/yarn.lock') }}
#          restore-keys: |
#            node-modules-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
#      - name: install dependencies
#        run: yarn --frozen-lockfile
#        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn lint
      - run: yarn test
